framework:
    messenger:
        transports:
            async:
                dsn: 'doctrine://default'
                options:
                    table_name: 'messenger_messages'
        routing:
            'App\Message\UploadMessage': async
            'App\Message\ProcessScanMessage': async
