framework:
    notifier:
        chatter_transports:
            slack: '%env(SLACK_DSN)%'  # Slack transport
            # telegram: '%env(TELEGRAM_DSN)%'  # Telegram transport (commented out)

        texter_transports:
            smtp: '%env(MAILER_DSN)%'  # Email transport
            # twilio: '%env(TWILIO_DSN)%'  # Twilio transport (commented out)
            # nexmo: '%env(NEXMO_DSN)%'  # Nexmo transport (commented out)

        channel_policy:
            # use chat/slack, sms/twilio or sms/nexmo
            urgent: ['email', 'slack']
            high: ['email', 'slack']
            medium: ['email', 'slack']
            low: ['email', 'slack']

        admin_recipients:
            - { email: admin@example.com }
